In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [6]:
df = pd.read_csv("data/df_july.csv")

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1754466 entries, 0 to 1754465
Data columns (total 26 columns):
city                           object
bar_id                         int64
order_id                       int64
order_time                     object
order_item_id                  int64
title                          object
category_id                    float64
beer_brand_id                  int64
beer_serving_type_id           int64
beer_volume                    float64
item_qty                       float64
sales_before_tax               float64
sales_inc_tax                  float64
guest_count                    int64
waiter_id                      float64
country                        object
country_id                     int64
state                          object
state_id                       int64
timezone                       object
bar_type_id                    int64
status                         int64
last_status                    int64
is_bulk                        int64
bar_type                       object
data_availability_status_id    int64
dtypes: float64(6), int64(13), object(7)
memory usage: 348.0+ MB

In [8]:
df.head()

,city,bar_id,order_id,order_time,order_item_id,title,category_id,beer_brand_id,beer_serving_type_id,beer_volume,...,country_id,state,state_id,timezone,bar_type_id,status,last_status,is_bulk,bar_type,data_availability_status_id
0,Trois-Rivières,2182,649875004,2019-07-18 09:12:44.000,64987500402,BACON,2.0,0,0,0.0,...,195,Québec,46,America/Toronto,10,12,0,0,Casual Dining,1
1,Trois-Rivières,2182,649875004,2019-07-18 09:12:44.000,64987500403,PAIN BLANC,2.0,0,0,0.0,...,195,Québec,46,America/Toronto,10,12,0,0,Casual Dining,1
2,Trois-Rivières,2182,649875004,2019-07-18 09:12:44.000,64987500400,GRASSE MATINEE,5.0,0,0,0.0,...,195,Québec,46,America/Toronto,10,12,0,0,Casual Dining,1
3,Trois-Rivières,2182,649875004,2019-07-18 09:12:44.000,64987500401,BROUILLÉ,2.0,0,0,0.0,...,195,Québec,46,America/Toronto,10,12,0,0,Casual Dining,1
4,Port Stanley,3383,649932765,2019-07-18 12:19:29.000,64993276502,Pickeral & Chips,2.0,0,0,0.0,...,195,Ontario,49,America/Toronto,1,12,0,0,Bar/Pub,1

In [10]:
df.city.value_counts()

Toronto             320888
Ottawa              172689
Vancouver           117234
Montreal            103009
London               69177
Mississauga          62267
Winnipeg             51495
Québec               48342
Victoria             48091
Gatineau             36378
Brampton             32438
Burlington           28855
Huntsville           25661
Kingston             24996
Halifax              23692
Laval                21220
Whitby               20555
Mont-Tremblant       20152
Barrie               19905
Pickering            19734
Trois-Rivières       19147
Abbotsford           18481
Saskatoon            17009
Granby               16147
Goderich             15936
Newmarket            15198
Markham              14675
Longueuil            14483
Kitchener            14392
Richmond Hill        14369
                     ...
Surrey                6793
Kelowna               5908
Prince George         5737
Sherbrooke            5545
Port Stanley          5370
Cambridge             5212
Chambly               5124
Sainte-Adèle          4678
Rimouski              4444
Burnaby               4034
Duncan                3841
Sorel-Tracy           3394
Vaughan               3025
Repentigny            2934
Mirabel               2896
Richmond              2388
Orleans               2242
Cowansville           2110
Matane                2000
Thunder Bay           1819
Saint-Romuald         1359
Lavaltrie             1168
Drummondville          977
Saint-Eustache         902
Saint-Jérôme           740
Vaudreuil-Dorion       649
Blainville             579
Lévis                  542
Shawinigan             268
Joliette               238
Name: city, Length: 84, dtype: int64